# Generated by Django 3.2.6 on 2022-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
